### ISSUE TITLE
[CHECKLIST] Launch prep

### ISSUE THREAD

**Issue by 1xstj** [webb-tools/tangle-restaking-parachain#20]
- [x] https://github.com/webb-tools/tangle-restaking-parachain/issues/11
- [x] Remove all democracy/council pallets and use sudo
- [x] Setup a basic runtime for crowdloan bid, reserve parachain-id and add to config
- [x] Setup polkadot runtime
- [x] Cleanup service binary and upgrade to latest polkadot version
- [x] Deploy to public testnet (rococo/newer) to test xcm messages with other parachains
- [ ] https://github.com/webb-tools/tangle-restaking-parachain/issues/21
